---
title: "Simulation Report"
output: html_notebook
---

```{r setup, include=FALSE}
library(ggplot2)

source("simulation_functions/MIC_utils.R")
source("simulation_functions/np_simulation.R")
source("simulation_functions/ph_simulation.R")
source("simulation_functions/po_simulation.R")
source("simulation_functions/real_simulation.R")
source("simulation_functions/generic_simulation.R")
```




#Data visualization 
```{r}

df <- transform_df(simulate_data_real(n = 1000)$dataframe, score_max = 11)
mean(df$T)

df_ <- df %>% filter(race == 0, sex == 1)

nrow(df %>% filter(Indicator == 1)) / nrow(df)

mean(df$T)

barplot(table(df_$T),
        main = "Bar Plot of Discrete Event Times",
        xlab = "Event Time (T)",
        ylab = "Frequency",
        col = "lightblue")

barplot(table(df$Delta),
        main = "Bar Plot of Delta",
        xlab = "Delta",
        ylab = "Frequency",
        col = "lightblue")

cor(df$T, df$Delta)

time <- system.time({
  fit_ <- MIC(df, user_formula = "cont + factor(sex) + factor(race)", method = "ph")
})
fit <- MIC(df, method = "pred.adj")

fit$meanT
fit_$meanT


plot(1:10, pmf(fit_$model, cov= list(race = 0, sex = 0, cont = 80), max_time = 10)$y)
#print(fit)
#print(fit_)

df
time
```
```{r}
library(microbenchmark)

mb <- microbenchmark(
  old = simulate_data_po_old(1000, seed = 100),
  new = simulate_data_po(    1000, seed = 100),
  times = 50
)
print(mb)

```

```{r}
res <- simulate_data_po(n = 400)
cond_pmf <- res$cond_pmf
cond_pmf(0, 0, 0)

```

```{r}
system.time({
  p_result <- run_simulations(setup = 0, m = 100, sim_model = c("simulate_data_po", "simulate_data_ph"), model = c("po", "ph"), boot = TRUE)
  print(p_result)
})

summarize_results(p_result, file = "results.csv")
```
```{r}
plot_results_list(p_result)
```

```{r}
#result<- run_simulations(setup = 0, m = 2)
#print(result)
#save(result, file = "simulation_results/RData/April_18_2025_simulation.RData")
system.time({
  for(setup in seq(0.1, 0.5, by = 0.1)){
    print("setup")
    print(setup)
    p_result <- run_simulations(setup = setup, m = 100, sim_model = c("simulate_data_po"), model = c("np","ph","po","pred","pred.adj"), boot = FALSE)
    print(p_result)
  }
})



```
